Base certificate hostname on api url
3scale-qe/3scale-tests pull request #115
Opened 2022-01-31 10:53 UTC by pehala

Previous implementation derived the hostname from 3scale superdomain and expected 3scale to be configured in a specific way. This PR changes that to make this work on any 3scale configuration as long as the OpenShift has standard URLs (api.<cluster_superdomain> and apps.<cluster_superdomain>)

@mganisin It should fix the failure both with RHOAM and IBM

2022-02-01 19:01 UTC, mganisin requested changes

2022-02-02 09:27 UTC, pehala commented on testsuite/openshift/client.py
> +    def get_api_url(self):
Changed to `api_url` and property

2022-02-02 16:32 UTC, mganisin approved these changes

2022-02-03 09:21 UTC, JaurbanRH approved these changes

2022-02-03 13:33 UTC, merged