Persistence plugin
3scale-qe/3scale-tests pull request #181
Opened 2022-03-14 13:59 UTC by JaurbanRH

Change tests so make speedrun is compatible with pytest persistence plugin and add plugin dependency to Pipfile.

2022-03-16 13:34 UTC, mdujava requested changes

2022-03-16 13:34 UTC, mdujava commented on testsuite/tests/apicast/policy/url_rewriting/test_url_rewriting_policy_append.py
> +    assert hits_before + 5 == hits_after
values are swapped:
actual == expected

2022-03-16 13:34 UTC, mdujava commented on testsuite/tests/apicast/policy/url_rewriting/test_url_rewriting_policy_insert_above_apicast.py
> +    assert hits_before + 5 == hits_after
values are swapped:
actual == expected

2022-03-16 13:38 UTC, mganisin commented on testsuite/tests/apicast/auth/test_update_staging.py
> +@pytest.mark.sandbag  # incompatible with persistence plugin
rm -rf

2022-03-16 13:38 UTC, mganisin commented on testsuite/tests/apicast/policy/batcher/test_batcher_policy_mapping_rules.py
> +@pytest.mark.sandbag  # incompatible with persistence plugin
rm -rf

2022-03-16 14:33 UTC, mdujava submitted a review, later dismissed

2022-03-24 10:33 UTC, pehala requested changes
I have found multiple failures in `system/` and `grafana/` (testsuite/tests/grafana/test_dashboards.py) directories.
Notably:
```
FAILED testsuite/tests/system/analytics/test_analytics.py::test_hits_service - assert 20 == (6 + 4)
FAILED testsuite/tests/system/analytics/test_backend_analytics.py::test_analytics - assert 10 == 5
FAILED testsuite/tests/system/mapping/test_mapping_rules_matching_order.py::test_mapping_rules_matching_order - assert 4 == 2
FAILED testsuite/tests/system/mapping/test_mapping_with_escape_sequence.py::test_mapping_with_escape_sequence - assert 2 == 1
```

2022-03-24 10:33 UTC, pehala commented on testsuite/tests/apicast/parameters/jaeger/test_jaeger_apicast_integration.py
> +CAPABILITIES = [Capability.JAEGER, Capability.CUSTOM_ENVIRONMENT]
This is not a skip. (Not sure how it got through in the first place :D)

2022-03-25 08:02 UTC, mganisin commented
If I run with this I always see persistence in the list of loaded plugins. I'd like to rather not see it there unless explicitly requested. It's worth to experiment with `-p` pytest option

2022-03-25 13:43 UTC, mganisin requested changes
Probably I'd like to see something like `-p no:persistence` in default options in Makefile to **ensure** this plugin excluded unless explicitly requested. (e.g. `if not --(store|load) in flags then add -p no:persistence`)

2022-04-11 14:54 UTC, mdujava approved these changes

2022-04-13 07:25 UTC, mganisin submitted a review, later dismissed

2022-04-20 07:59 UTC, pehala requested changes
A few tests are still failing, I believe a few of those that had their mark removed
```
FAILED testsuite/tests/apicast/test_hit_limit.py::test_retry_after - assert 200 == 429
FAILED testsuite/tests/apicast/apiap/test_backend_routing.py::test[empty_path-expect_ok1-expect_not_found1] - AssertionError: For path /anything/loud expected hits to be increased by 1
FAILED testsuite/tests/apicast/apiap/test_backend_routing.py::test[isolated_backends-expect_ok0-expect_not_found0] - AssertionError: For path /echo/anything/loud expected hits to be increased by 1
FAILED testsuite/tests/apicast/apiap/test_backend_routing.py::test[path_extension-expect_ok2-expect_not_found2] - AssertionError: For path /quotes/anything/test/anything/loud expected hits to be increased by 1
ERROR testsuite/tests/apicast/policy/tls/tls_upstream/tls_passthrough_connection_reuse/test_connection_reuse.py::test_connection_reuse - IndexError: list index out of range
ERROR testsuite/tests/system/test_unique_invoice_id.py::test_unique_invoice - threescale_api.errors.ApiClientError: Response(422 Unprocessable Entity): b'{"errors":{"users":["invalid"],"billing_address_name":[],"billing_address_ad...
ERROR testsuite/tests/system/test_unique_invoice_id.py::test_unique_invoice - threescale_api.errors.ApiClientError: Response(422 Unprocessable Entity): b'{"errors":{"base":["Cannot transition to cancelled"]}}'
ERROR testsuite/tests/system/mapping/test_mapping_rules_matching_order_multiple_backends.py::test[expect_ok0] - IndexError: list index out of range
```

2022-05-02 10:31 UTC, pehala approved these changes

2022-05-02 14:27 UTC, mdujava approved these changes

2022-05-03 11:31 UTC, merged