Add test for logging policy with custom date format
3scale-qe/3scale-tests pull request #232
Opened 2022-04-28 14:19 UTC by JaurbanRH

Test for https://issues.redhat.com/browse/THREESCALE-6594

2022-04-29 08:34 UTC, pehala commented on testsuite/tests/apicast/policy/logging/test_date_logging.py
> +    assert today in logs
You should use self-managed APIcast as if this test was run two times in a single day the previous value would be the same and also present in the logs.

2022-04-29 10:57 UTC, pehala approved these changes

2022-04-29 13:26 UTC, mganisin requested changes

2022-04-29 13:26 UTC, mganisin commented on testsuite/tests/apicast/parameters/test_date_logging.py
> +    """Customize the access logs format"""
`policy_settings` works nicely with predefined customized `service`. if that doesn't exist (to share simpler definition between other tests) neither `policy_settings` makes sense.

1. Either place policy definition directly to `service` fixture
2. or put the `service` fixture honoring `policy_settings` to conftest here or upstrairs

2022-04-29 13:32 UTC, mganisin commented on testsuite/tests/apicast/parameters/test_date_logging.py
> +
Sorry, I don't understand line no.21 :-)

2022-05-02 14:50 UTC, mdujava submitted a review, later dismissed

2022-05-02 17:58 UTC, pehala commented on testsuite/tests/apicast/parameters/test_date_logging.py
> +    pytest.mark.required_capabilities(Capability.LOGS),
I am missing skipif for version

2022-05-03 13:03 UTC, mganisin approved these changes

2022-05-04 08:02 UTC, pehala approved these changes

2022-05-04 08:06 UTC, merged