Session remove
3scale-qe/3scale-tests pull request #295
Opened 2022-06-19 12:19 UTC by jsmolar

Changed `Browser` fixture scope to module (was session before). With this necessary changes for login fixtures needed to be made. 
The session fixture was also removed with this PR.

2022-06-20 10:56 UTC, JaurbanRH submitted a review, later dismissed

2022-07-20 15:45 UTC, JaurbanRH approved these changes

2022-08-01 13:38 UTC, dhlavac requested changes
Please also document these changes in UI documentation, as they change the way how UI tests should be written

2022-08-01 13:38 UTC, dhlavac commented on testsuite/tests/ui/conftest.py
> +    webdriver = Webdriver(source=settings["fixtures"]["ui"]["browser"]["source"],
Is creating a variable necessary? The purpose is only to return an instance of webdriver.

2022-08-08 14:01 UTC, dhlavac commented
LGTM!

2022-08-08 18:59 UTC, mganisin approved these changes

2022-08-08 18:59 UTC, merged