Migrate image to centos-stream
3scale-qe/3scale-tests pull request #297
Opened 2022-06-20 11:02 UTC by pehala

- Migrate to centos-stream image
  - The old base image is based on centos7 and does support newer python images 
- Update python to 3.9
- ~~Remove explicit CA links~~
   - ~~Should be supplied through secret~~
- Remove unnecessary dependencies (`docker-client`, `openssh-client`)
   -  Docker is unused and OpenSSH shouldn't be needed as paramiko implements the protocol itself (@mdujava please verify)
- ~~Venv is now created inside workdir~~
- ~~Image is not buildable outside of VPN~~

2022-06-20 12:10 UTC, mdujava submitted a review, later dismissed
toolbox/paramiko works just fine

2022-06-22 12:17 UTC, mganisin requested changes

2022-06-23 11:28 UTC, pehala commented
@mganisin Reworked based on our discussions.

2022-06-27 11:54 UTC, mdujava submitted a review, later dismissed

2022-07-01 07:57 UTC, mganisin commented on Dockerfile
> +RUN useradd --no-log-init -u 1001 -G root -r -m default
this should be `-g root` and I would really like to see also `-r` removed (the latter is mild, however unless there is good reasoning I'd prefer to make sure `$HOME` exists; actually there is reference to `$HOME later in Dockerfile, likely to eradicate pipenv cache, so it is highly desirable to ensure it is properly set with correct access permissions)

2022-07-07 08:05 UTC, mganisin approved these changes

2022-07-07 10:41 UTC, mdujava approved these changes

2022-07-07 10:45 UTC, merged