Add test for backend search
3scale-qe/3scale-tests pull request #353
Opened 2022-07-29 10:23 UTC by JaurbanRH

2022-07-29 10:40 UTC, JaurbanRH commented
Quality check failed because of missing init file which is in PR #352

2022-08-01 12:42 UTC, dhlavac commented
@JaurbanRH why you don't include the init file in this PR as well?

2022-08-01 12:48 UTC, dhlavac commented on testsuite/tests/ui/search/test_backend_search.py
> +Rewrite of spec/ui_specs/users/users_search_spec.rb
Imho leftover from user search test

2022-08-09 09:36 UTC, JaurbanRH commented
#352 needs to be merged first.

2022-08-11 08:23 UTC, jsmolar approved these changes

2022-08-11 08:36 UTC, dhlavac requested changes
Same issue as PR #352

2022-08-16 13:24 UTC, dhlavac requested changes
PR still contains changes from #352 please remove them from this PR or apply coments from #352 to this PR as well

2022-08-16 13:24 UTC, dhlavac commented on testsuite/tests/ui/search/test_backend_search.py
> +        - you search account by email it will return the correct one
Incorrect test description, backends are not searchable by email or application

2022-08-16 13:24 UTC, dhlavac commented on testsuite/tests/ui/search/test_backend_search.py
> +def test_search_product(login, navigator, request, custom_ui_backend):
Incorrect name of the test

2022-08-16 13:24 UTC, dhlavac commented on testsuite/tests/ui/search/test_backend_search.py
> +        - you search account by base name it will return the correct ones (first 3)
search of backend not account

2022-08-16 13:24 UTC, dhlavac commented on testsuite/ui/views/admin/backend/__init__.py
> +        """Search in account table by given value"""
Search in  backend table

2022-08-16 13:24 UTC, dhlavac commented on testsuite/tests/ui/search/test_backend_search.py
> +        - you search account by non-existing-value it won't return anything
Backend no account

2022-08-23 08:30 UTC, closed without merging