Add tests for product search
3scale-qe/3scale-tests pull request #373
Opened 2022-08-23 09:30 UTC by JaurbanRH

2022-08-23 09:55 UTC, jsmolar commented on testsuite/tests/ui/search/test_product_search.py
> +@pytest.mark.xfail
This one should be not marked as failed

2022-08-23 10:04 UTC, jsmolar approved these changes

2022-08-23 11:37 UTC, dhlavac requested changes

2022-08-23 11:37 UTC, dhlavac commented on testsuite/tests/ui/search/test_product_search.py
> +    name = blame(request, "")
Same issue as #372 is it supposed to start with a dash?

2022-08-25 08:59 UTC, dhlavac approved these changes

2022-08-25 10:00 UTC, mganisin approved these changes

2022-08-25 10:00 UTC, merged