Add tests for backend search
3scale-qe/3scale-tests pull request #374
Opened 2022-08-23 09:35 UTC by JaurbanRH

2022-08-23 09:49 UTC, jsmolar submitted a review, later dismissed

2022-08-23 11:40 UTC, dhlavac requested changes

2022-08-23 11:40 UTC, dhlavac commented on testsuite/tests/ui/search/test_backend_search.py
> +    name = blame(request, "")
Should it start with a dash?

2022-08-25 08:57 UTC, dhlavac approved these changes

2022-08-25 09:59 UTC, mganisin approved these changes

2022-08-25 09:59 UTC, merged