Mail fix
3scale-qe/3scale-tests pull request #41
Opened 2021-11-19 13:01 UTC by palmieric

This PR update the mail tests to use ad-hoc application and service

2021-11-19 13:59 UTC, mganisin commented
Commits need refactor (likely squash)

2021-11-22 09:47 UTC, mganisin approved these changes

2021-11-22 09:54 UTC, mdujava commented on testsuite/tests/system/messages/mail_templates.yml
> +      of the <test_group> account.</p><p><b>Application details:</b></p><ul><li><b>Name:</b>
introducing trailing space

2021-11-22 10:58 UTC, palmieric commented on testsuite/tests/system/messages/mail_templates.yml
> +      of the <test_group> account.</p><p><b>Application details:</b></p><ul><li><b>Name:</b>
removed

2021-11-22 11:35 UTC, mdujava approved these changes

2021-11-22 11:49 UTC, mganisin commented
Multiple commits, likely squash needed

2021-11-22 19:30 UTC, mganisin requested changes
squash commits please

2021-11-24 12:27 UTC, mganisin approved these changes

2021-11-24 12:28 UTC, merged