Add tests for iamge checks
3scale-qe/3scale-tests pull request #497
Opened 2023-02-03 14:44 UTC by JaurbanRH

2023-02-20 12:06 UTC, mdujava requested changes

2023-02-20 12:06 UTC, mdujava commented on testsuite/tests/system/test_system_image.py
> +    expected_image = images.get("3scale")
ambiguous name, I would add _system_app to it

2023-02-20 12:06 UTC, mdujava commented on testsuite/tests/system/test_system_image.py
> +    lookup = openshift().do_action("get", ["is/amp-system", "-o", "yaml"])
is there a reason why this is checking `is` and not the `pod` itself?

2023-02-20 12:06 UTC, mdujava commented on config/settings.yaml.tpl
> +    3scale: "" # Image of deployed 3scale system
I would specify that it's system-app

2023-03-01 14:39 UTC, pehala commented on testsuite/tests/images/test_images_check.py
> +    lookup = openshift.do_action("get", [f"dc/{deployment_config}", "-o", "yaml"])
```
lookup = openshift.do_action("get", [f"dc/{deployment_config}", "-o", "yaml"], parse_output=True)
digest = lookup.model.spec.template.spec.containers[-1].image.split(":")[-1)
```

2023-03-01 14:39 UTC, pehala commented on config/settings.yaml.tpl
> +      digest: # Digest of deployed 3scale backend
either:
`      digest: # Multi-arch manifest digest`
or
`      manifest_digest: # Multi-arch manifest digest`

2023-03-20 07:55 UTC, mganisin commented
`oc cluster-info dump | jq '.items[].metadata.labels["kubernetes.io/arch"]'`

2023-03-22 11:05 UTC, pehala commented on testsuite/tests/images/test_images_check.py
> +    expected_image = images.get(f"{image}")
No need for string formatting

2023-03-22 11:07 UTC, mganisin commented on testsuite/tests/conftest.py
> +def cluster_arch(openshift):
This should be `openshift.arch` not a fixture

2023-03-23 12:49 UTC, pehala submitted a review, later dismissed

2023-04-05 07:53 UTC, mganisin approved these changes

2023-04-05 08:12 UTC, pehala commented on testsuite/tests/images/test_images_check.py
> +    namespace = testconfig["openshift"]["projects"]["threescale"]['name']
Why do you need the namespace, shouldn't just openshift() do the job?

2023-04-05 08:12 UTC, pehala commented on testsuite/tests/images/test_images_check.py
> +    return openshift.get_apicast_operator().object()
`staging_gateway.openshift.get_apicast_operator().object()`, you already create SelfManagedApicast

2023-04-05 08:12 UTC, pehala commented on testsuite/tests/images/test_images_check.py
> +    gw = gateway(kind=SelfManagedApicast, staging=True, name=blame(request, "gw"))
I would use just OperatorApicast, I dont see any reason to run it on Template

2023-04-05 09:21 UTC, pehala approved these changes

2023-04-05 12:38 UTC, dhlavac approved these changes

2023-04-06 07:07 UTC, merged