Implement environmental varables in OperatorApicast through CRD
3scale-qe/3scale-tests pull request #55
Opened 2021-11-29 13:12 UTC by pehala

* It is possible to set/get environmental variables in `OperatorApicast` through `environ()` method.
   * CRD is used instead of directly changing the deployment
   * delete is not yet supported, since it is not used at all
*  Not all environmental variables are implemented yet
   * This will be done in subsequent PRs
* Extracted `Properties` interface from `Environ` and made `environ()` method return `Properties`
* Add `OperatorEnviron` which handles transforming from env vars to CRD names
* Changed tests to use `SelfManagedApicast` instead of `TemplateApicast` where possible.
   * This means the tests will use `OperatorApicast` on OCP4 and `TemplateApicast` on ocp3  
   * Choose opt-in approached as it will be clearly visible from PRs which tests are now supported on OCP4
 
 If the number of files this PR changes is too much, it is possible to split this in two, where one is the first commit only.

2021-11-29 13:42 UTC, mganisin submitted a review, later dismissed

2021-11-30 09:44 UTC, mdujava requested changes

2021-11-30 09:44 UTC, mdujava commented on testsuite/openshift/crd/apicast.py
> +        Workaround until https://github.com/openshift/openshift-client-python/pull/102 is merged
It was merged.

2021-11-30 13:53 UTC, mdujava approved these changes

2021-12-01 19:52 UTC, mganisin approved these changes

2021-12-01 19:52 UTC, merged