Fix api docs tests
3scale-qe/3scale-tests pull request #595
Opened 2023-04-20 08:01 UTC by JaurbanRH

2023-04-20 08:04 UTC, mganisin approved these changes

2023-04-20 08:22 UTC, pehala approved these changes

2023-04-24 13:59 UTC, dhlavac requested changes

2023-04-24 13:59 UTC, dhlavac commented on testsuite/ui/widgets/__init__.py
> +        element = self.browser.element("//button[@aria-label='Options menu']")
Please add a note that this is for opening the menu because the locator matches all buttons and Select does work

2023-04-25 09:53 UTC, dhlavac approved these changes

2023-04-25 10:18 UTC, mganisin approved these changes

2023-04-25 10:18 UTC, merged