Switch OpenTracing for a OpenTelemetry test
3scale-qe/3scale-tests pull request #656
Opened 2023-05-31 14:33 UTC by mdujava

Coexistence of OpenTelemetry and OpenTracing tests will work in case of reverting "[Remove depricated OpenTracing integration test](https://github.com/3scale-qe/3scale-tests/commit/cb51b26621e0eb0eb4f2324a2a189473d15203be)" commit.

2023-06-01 08:48 UTC, mganisin requested changes

2023-06-01 08:48 UTC, mganisin commented on testsuite/jaeger.py
> +    def apicast_config_open_tracing(self, configmap_name, service_name):
Don't change eixsting  interfaces

2023-06-01 08:48 UTC, mganisin commented on testsuite/gateways/apicast/operator.py
> +    def connect_open_tracing(self, jaeger):
don't change existing interfaces

2023-06-01 14:38 UTC, mdujava commented on testsuite/gateways/apicast/operator.py
> +    def connect_open_telemetry(self, jaeger):
Updated `apicast/system.py` and `apicast/template`.

2023-06-01 14:39 UTC, mdujava commented on testsuite/jaeger.py
> +            configmap_name: f"""# "otlp" is the only supported exporter in APIcast
moved config to resource file

2023-06-05 18:13 UTC, mganisin commented on testsuite/tests/apicast/parameters/jaeger/test_open_telemetry_apicast_integration.py
> +def test_open_telemetry_apicast_integration(api_client, jaeger, jaeger_service_name):
no reference to relevant jira? (open telemetry support)

2023-06-06 10:56 UTC, mganisin approved these changes

2023-06-15 05:12 UTC, mganisin approved these changes

2023-06-15 07:48 UTC, pehala approved these changes

2023-06-15 09:45 UTC, merged