Add test for admin password reset
3scale-qe/3scale-tests pull request #714
Opened 2023-07-25 08:21 UTC by JaurbanRH

2023-07-25 14:15 UTC, dhlavac requested changes

2023-07-25 14:15 UTC, dhlavac commented on testsuite/tests/ui/test_reset_password.py
> +    reset_link = re.findall("https://.*\\r", message["items"][0]["Content"]["Body"])[0][:-1]
when you use `re.search(r"(?P<url>https?://[^\s]+)", message["items"][0]["Content"]["Body"]).group("url")`  you will have only url (not list) without need to remove characters from it

2023-07-25 14:15 UTC, dhlavac commented on testsuite/tests/ui/test_reset_password.py
> +"""Test for reset password"""
Imho it can be added as an extension to the current test, no need to create a separate test for this.

2023-07-25 14:15 UTC, dhlavac commented on testsuite/tests/ui/test_reset_password.py
> +    page.change_password("password")
Maybe some generated password? (it can run on public instances)

2023-07-31 12:15 UTC, mganisin approved these changes

2023-07-31 12:43 UTC, jsmolar approved these changes

2023-08-02 10:47 UTC, dhlavac approved these changes

2023-08-02 10:52 UTC, merged