Add test that system is not sending mail notification to suspended users
3scale-qe/3scale-tests pull request #741
Opened 2023-09-07 11:43 UTC by JaurbanRH

2023-09-12 10:26 UTC, dhlavac requested changes

2023-09-12 10:26 UTC, dhlavac commented on testsuite/tests/ui/mail_and_messages/test_mail_to_suspended_user.py
> +@pytest.mark.issue("https://issues.redhat.com/browse/THREESCALE-8903")
Please add mark `pytest.mark.skipif("TESTED_VERSION < Version('2.14')")` or correct fix version.

2023-09-12 10:26 UTC, dhlavac commented on testsuite/tests/ui/mail_and_messages/test_mail_to_suspended_user.py
> +def test_mail_to_suspended_user(provider_account_user, ui_account, mailhog_client):
missing login

2023-09-12 12:03 UTC, dhlavac approved these changes

2023-09-13 07:32 UTC, jsmolar approved these changes

2023-09-14 12:33 UTC, merged