Change UI policy tests based on MAS 0.11.8
3scale-qe/3scale-tests pull request #754
Opened 2023-10-16 18:06 UTC by JaurbanRH

2023-10-17 16:45 UTC, mdujava requested changes
I do get errors/failures when executing with this patch:
```
testsuite/tests/ui/policies/test_policies.py::test_... - TypeError: ThreescaleButton.__init__() got multiple values for argument 'text'
testsuite/tests/ui/policies/test_referrer_policy.py::test_... - TypeError: ThreescaleButton.__init__() got multiple values for argument 'text'
testsuite/tests/ui/policies/test_tls_termination_policy_in_ui.py::test_... - TypeError: ThreescaleButton.__init__() got multiple values for argument 'text'
```

2023-10-18 12:24 UTC, mdujava submitted a review, later dismissed

2023-10-18 14:27 UTC, dhlavac commented on testsuite/ui/widgets/__init__.py
> +        """Returns a WebElement for given item name.
Please correct description

2023-10-19 06:59 UTC, mdujava approved these changes

2023-10-19 08:40 UTC, dhlavac approved these changes

2023-10-19 08:40 UTC, merged