Add test for token introspection policy
3scale-qe/3scale-tests pull request #806
Opened 2024-02-21 14:56 UTC by JaurbanRH

2024-02-22 13:37 UTC, dhlavac requested changes

2024-02-22 13:37 UTC, dhlavac commented on testsuite/tests/apicast/policy/test_token_introspection_threescale_endpoint.py
> +    response = client.get("/get", headers={"authorization": "Bearer " + access_token})
convention is to use the header name in the form  `Authorization` , please use f string for string interpolation

2024-02-22 13:37 UTC, dhlavac commented on testsuite/tests/apicast/policy/test_token_introspection_threescale_endpoint.py
> +    new_response = client.get("/get", headers={"authorization": "Bearer " + access_token})
convention is to use the header name in the form  `Authorization` , please use f string for string interpolation

2024-02-28 13:01 UTC, dhlavac approved these changes

2024-02-28 13:13 UTC, mdujava approved these changes

2024-02-28 13:24 UTC, merged