Change directory where tls certificates are stored
3scale-qe/3scale-tests pull request #808
Opened 2024-02-26 15:43 UTC by JaurbanRH

2024-02-28 13:12 UTC, mdujava approved these changes

2024-02-28 15:53 UTC, dhlavac commented
@JaurbanRH there are still some tests marked as no persistence in the tls tests folder, is it correct ? Or should we remove marks from that tests ?

2024-02-28 15:57 UTC, mdujava requested changes
`resultsdir` should be set by Makefile, but running `make` without setting `resultsdir` explicitly, certs are stored in `/tmp`; maybe `resultsdir` is not exported so pytests does not see it?

2024-02-28 15:57 UTC, JaurbanRH commented
> @JaurbanRH there are still some tests marked as no persistence in the tls tests folder, is it correct ? Or should we remove marks from that tests ?

@dhlavac Yes that is correct. Those test need complete rewrite to be compatible with persistence plugin.

2024-03-11 15:28 UTC, mdujava approved these changes

2024-03-12 12:49 UTC, merged