Add first draft to configure rhsso/rhbk via settings
3scale-qe/3scale-tests pull request #836
Opened 2024-05-20 14:57 UTC by mdujava

2024-06-03 12:22 UTC, mijaros requested changes
I think that the changes are well written and i understand that the nesting is relict of older development, but why don't fix it now?

2024-06-03 12:22 UTC, mijaros commented on testsuite/dynaconf_loader.py
> +    return None
This depth seems kinda redundant and deep, every positive branch ends with the return so nesting the code into the except branches is not good idea to be honest.

2024-06-03 12:22 UTC, mijaros commented on testsuite/tests/conftest.py
> +    items[:] = selected
I want on the record that I don't like this! :-)

2024-06-03 12:26 UTC, mijaros approved these changes
Ok, this looks very promissing.

2024-06-06 17:39 UTC, dhlavac commented on testsuite/tests/conftest.py
> +    items[:] = selected
Cannot be simplified to ?
`   selected_fixtures = {"rhsso_setup"}
    deselected = []

    sso_only_opt = config.option.sso_only
    selected = []

    for item in items:
        for marker in item.iter_markers(name="issue"):
            issue = marker.args[0]
            issue_id = issue.rstrip("/").split("/")[-1]
            item.user_properties.append(("issue", issue))
            item.user_properties.append(("issue-id", issue_id))

        if sso_only_opt and not any(fixture in selected_fixtures for fixture in item.fixturenames):
            deselected.append(item)
        else:
            selected.append(item)

    items[:] = selected

    if deselected:
        config.hook.pytest_deselected(items=deselected)`

2024-06-11 10:02 UTC, JaurbanRH submitted a review, later dismissed

2024-06-11 10:14 UTC, mkudlej approved these changes
LGTM except of one change in Pipfile, which should be removed I think.

2024-06-11 10:14 UTC, mkudlej commented on Pipfile
> +ipdb = "*"
This should e part of different PR.

2024-06-11 12:09 UTC, mkudlej approved these changes

2024-06-12 11:16 UTC, dhlavac commented on testsuite/tests/conftest.py
> +        if sso_only_opt and not any(fixture in selected_fixtures for fixture in item.fixturenames):
we need to deselect performance tests from sso tag, there are 4 tests from performance

2024-06-12 11:36 UTC, dhlavac approved these changes

2024-06-12 11:36 UTC, merged